### ISSUE TITLE
Mise en correction

### ISSUE THREAD

**Issue by AlizeeBouhana** [PolytechLyon/isi3-tests-2019-bouhana-galochet#1]
Bonjour,
Voici notre rendu pour le TP de tests unitaires.

**Comment by Slashgear** [comment]
Faux

>Qu'est-ce qu'un test boite noire ?
On teste sans connaissance de l'implémentation des tests.
Qu'est-ce qu'un test boite blanche ?
On teste en connaissance de l'implémentation des test.

Internet est votre amis pour corriger cela

Sinon le reste est ok 😄

**Comment by DamGLT** [comment]
Instant Wikipedia / remise sur le droit chemin effectué.
